### ISSUE TITLE
Lien de titre header mort

### ISSUE THREAD

**Issue by raphaelbrugier** [clescot/clescot.github.com#1]
Bonjour,

Dans le header "Le blog de Charles Lescot." le lien renvoie vers "/" au lieu de "/blog/".
Ce qui renvoie vers une page vide.

(Excellents articles sur les test btw!)

**Comment by clescot** [comment]
Bonjour,
merci pour le feedback concernant ce lien mort.
=> je vais le mettre à jour rapidement vers une page me présentant.

Merci aussi pour les retours concernant les articles sur les tests;
j'espère que les prochains articles vous plairont aussi.

Charles.
